# Define sensitive files to be mounted securely in containers
secrets:
  db_user_password:
    file: ../secrets/db_user_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

# Isolated internal network for container-to-container communication
networks:
  inception:
    driver: bridge
  
# Persistent storage mapped to specific host paths
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tsilva/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/tsilva/data/wordpress

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    env_file:
      - .env
    secrets:
      - db_user_password
      - db_root_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress
    env_file:
      - .env
    secrets:
      - db_user_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    restart: on-failure

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    ports:
      - "443:443"
    restart: on-failure
